spring.application.name=todolist-api

# ===============================
# Database
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5431/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ===============================
# Flyway
# ===============================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
